import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {mergeGeometries} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
const $=s=>document.querySelector(s);
const viewport=$('#viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color('#e7e9e7');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(viewport.clientWidth,viewport.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;document.querySelector('#viewport').appendChild(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.addEventListener('pointerdown',()=>renderer.domElement.focus({preventScroll:true}));
let compactTextures=innerWidth<=700||matchMedia('(pointer: coarse)').matches||(navigator.deviceMemory&&navigator.deviceMemory<=4);const sizedTextures=new Set();
function sizeAtlas(m){if(!m.map||sizedTextures.has(m.map)||!/^Baked \/ /.test(m.name))return;sizedTextures.add(m.map);if(!compactTextures)return;const hero=/_11_z0[012]_|_13_/.test(m.name);const cap=hero?1024:512;const im=m.map.image;if(!im||Math.max(im.width,im.height)<=cap)return;const scale=cap/Math.max(im.width,im.height),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);m.map.image=c;m.map.needsUpdate=true;im.close?.();}
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;
const camera=new THREE.PerspectiveCamera(50,viewport.clientWidth/viewport.clientHeight,.08,500);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.09;controls.minDistance=.3;controls.maxDistance=230;controls.maxPolarAngle=Math.PI*.98;
scene.add(new THREE.HemisphereLight(0xe7f2ff,0x9c8e75,.6));const sun=new THREE.DirectionalLight(0xfff4df,1.4);sun.position.set(45,70,20);scene.add(sun);const fill=new THREE.DirectionalLight(0xd8eaff,.5);fill.position.set(-35,25,-25);scene.add(fill);
const cv=v=>new THREE.Vector3(v[0],v[2],-v[1]);
const views={
 exterior:{p:[84,-87,62],t:[-1,1,12],label:'Exterior · inferred overall massing',fov:44},
 east:{p:[12,-.8,1.75],t:[32.6,.1,4.9],label:'East atrium · heritage wall & entrance',fov:64},
 west:{p:[31,2,1.7],t:[12,0,.7],label:'03:30 · entrance atrium',fov:45.75},
 landing:{p:[-11.5,-12.8,5.8],t:[-4.5,-3.5,5.0],label:'14:30 · illuminated central stair',fov:45.75},
 room2133:{p:[1,-6.85,5.8],t:[2.42,-2.3,5.52],label:'14:52 · room 2133',fov:29.84},
 theatre:{p:[15,12.7,2.1],t:[20,23,.9],label:'06:30 · raked lecture theatre',fov:29.84},
 boards:{p:[14.776,15.969,2.416],t:[19.661,8.57,3.689],label:'07:30 · sliding chalkboards',fov:45.75},
 lantern:{p:[-1,-1,2],t:[-12,-7,16],label:'Central lantern · inferred circulation',fov:80},
 street:{p:[60,10,1.75],t:[33.4,10,2.5],label:'00:30 · St. George Street entrance',fov:36.2},
 cutaway:{p:[67,-77,63],t:[-1,0,7],label:'Cutaway · atrium structure & circulation',fov:48}
};
function fitCamera(){const mobile=innerWidth<=700;const w=viewport.clientWidth,h=mobile?viewport.clientHeight:Math.min(viewport.clientHeight,w*9/16);camera.aspect=w/h;camera.fov=mobile?60:(views[view]?.fov||45);camera.updateProjectionMatrix();renderer.setSize(w,h);needsRender=true;}
let sourceComponents=0;let model,view='exterior',isCut=false,edges=[],hasEdges=false;let activeKeys=new Set();
const closedMaterials=new WeakMap(),cutawayMaterials=new Map();
function cut(v){needsRender=true;isCut=v;$('#cut').checked=v;if(!model)return;model.traverse(o=>{
 if(o.isMesh){if(!closedMaterials.has(o))closedMaterials.set(o,o.material);const original=closedMaterials.get(o);if(v&&/^Baked \/ /.test(original.name)&&o.userData.layer?.startsWith('01')){if(!cutawayMaterials.has(original))cutawayMaterials.set(original,new THREE.MeshLambertMaterial({color:'#bfc4bf',side:THREE.DoubleSide}));o.material=cutawayMaterials.get(original);}else o.material=original;const g=o.userData.layer||'';const shell=g.startsWith('02')||g.startsWith('07');const context=o.userData.context;o.visible=!(v&&(shell||context))&&(!g.startsWith('09')||$('#trees').checked);}
});}
function setView(key){view=key;const v=views[key];const mobile=innerWidth<=700;const targets={landing:[-10,-8.4,5.3],room2133:[1.35,-2.3,5.55]};const target=mobile?(targets[key]||v.t):v.t;camera.position.copy(cv(v.p));controls.target.copy(cv(target));if(mobile&&['exterior','cutaway','street'].includes(key)){camera.position.sub(controls.target).multiplyScalar(1.45).add(controls.target);}fitCamera();controls.update();cut(key==='cutaway');$('#viewname').textContent=v.label;const times={landing:870,room2133:892,theatre:390,boards:450,street:30,west:210};const seconds=times[key];$('#source').href=seconds!==undefined?`https://www.youtube.com/watch?v=GGaJsGu_5zA&t=${seconds}s`:'https://alecjacobson.github.io/astra-dgp/gallery.html';$('#source').textContent=seconds!==undefined?'Watch this part of the source tour ↗':'See the video/render comparisons ↗';document.querySelectorAll('[data-view]').forEach(b=>{const on=b.dataset.view===key;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});renderer.toneMappingExposure=1; if(innerWidth<=700){document.body.classList.remove('mobile-controls');$('#hide').textContent='Views & controls';}fitCamera();}
window.bahen={setView,cut,get state(){return{loaded:!!model,sourceComponents,textureMode:compactTextures?'compact':'full',...textureStats(),view,cutaway:isCut,meshes:model?countMeshes(model):0,camera:camera.position.toArray(),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,visibleMeshes:model?model.children.filter(o=>o.visible).length:0,layers:model?[...new Set(model.children.map(o=>o.userData.layer))]:[]}}};
function textureStats(){const seen=new Set();let bytes=0,maxAtlas=0;if(model)model.traverse(o=>{if(!o.isMesh)return;for(const m of [closedMaterials.get(o)||o.material]){if(!m.map||seen.has(m.map))continue;seen.add(m.map);const im=m.map.image;if(!im)continue;bytes+=im.width*im.height*4*4/3;if(/^Baked \/ /.test(m.name))maxAtlas=Math.max(maxAtlas,im.width,im.height);}});return{estimatedTextureMiB:Math.round(bytes/1048576),maxAtlasSize:maxAtlas};}
function countMeshes(o){let n=0;o.traverse(c=>{if(c.isMesh)n++});return n;}
function loaded(gltf){model=gltf.scene;scene.add(model);let mats=new Set();model.traverse(o=>{
 if(o.isMesh){let p=o.parent;while(p&&!/^\d\d[ _]/.test(p.name))p=p.parent;o.userData.layer=p?.name||'';
 const mm=Array.isArray(o.material)?o.material:[o.material];mm.forEach(m=>{if(mats.has(m))return;mats.add(m);sizeAtlas(m);m.side=THREE.DoubleSide;if(m.isMeshBasicMaterial||/^Baked \/ /.test(m.name)){m.toneMapped=false;}if(/Glass|glazing|Frosted/i.test(m.name)&&m.isMeshPhysicalMaterial){const channel=/channel/i.test(m.name),frost=/Frosted/i.test(m.name);m.transmission=channel?.38:frost?.22:.92;m.transparent=false;m.opacity=1;m.depthWrite=true;m.roughness=channel?.38:frost?.3:.012;m.metalness=0;m.ior=1.48;m.thickness=.012;m.color.set(channel?'#c1d0cb':frost?'#90b4c8':'#eff7f4');}if(m.map){m.map.anisotropy=renderer.capabilities.getMaxAnisotropy();}m.needsUpdate=true;});}
});
 // Batch by material and layer after transform evaluation; source GLB stays editable.
 sourceComponents=gltf.asset?.extras?.source_components||countMeshes(model);model.updateMatrixWorld(true);const buckets=new Map();model.traverse(o=>{if(!o.isMesh)return;const ctx=o.name.startsWith('Koffler')||o.userData.cutaway_shell===true;const key=o.userData.layer+'|'+o.material.uuid+'|'+ctx;let b=buckets.get(key);if(!b){b={layer:o.userData.layer,context:ctx,material:o.material,geometries:[]};buckets.set(key,b)}let g=o.geometry.clone();g.applyMatrix4(o.matrixWorld);if(g.index)g=g.toNonIndexed();for(const a of Object.keys(g.attributes))if(!['position','normal','uv'].includes(a))g.deleteAttribute(a);if(!g.attributes.uv)g.setAttribute('uv',new THREE.BufferAttribute(new Float32Array(g.attributes.position.count*2),2));b.geometries.push(g)});
 const root=new THREE.Group();for(const b of buckets.values()){const g=mergeGeometries(b.geometries,false);if(!g)throw new Error('Geometry batching failed');const mesh=new THREE.Mesh(g,b.material);mesh.name=b.layer;mesh.userData={layer:b.layer,context:b.context};root.add(mesh);b.geometries.forEach(g=>g.dispose())}scene.remove(model);model=root;scene.add(model);
 $('#loading').hidden=true;$('#modelstats').textContent='Reconstruction in metres · drag to explore';setView(location.hash.slice(1) in views?location.hash.slice(1):'landing');window.dispatchEvent(new Event('modelready'));
}
const loader=new GLTFLoader();
// Decode lighting atlases at display size on phones, before GPU upload.
if(compactTextures)loader.register(parser=>({name:'BAHEN_compact_lighting',loadTexture(index){const def=parser.json.textures[index],src=parser.json.images[def.source];if(!src||!/^\d\d_/.test(src.name||'')||!parser.textureLoader.isImageBitmapLoader)return null;const cap=/_11_z0[012]_|_13_/.test(src.name)?1024:512;const decoder=new THREE.ImageBitmapLoader(parser.options.manager).setOptions({premultiplyAlpha:'none',resizeWidth:cap,resizeHeight:cap,resizeQuality:'high'});return parser.loadTextureImage(index,def.source,decoder);}}));
if(window.MODEL_BASE64){const bin=Uint8Array.from(atob(window.MODEL_BASE64),c=>c.charCodeAt(0));loader.parse(bin.buffer,'',loaded,error);}else loader.load('bahen-lit.glb',loaded,e=>{$('#loading').textContent=e.total?`Loading model… ${Math.round(e.loaded/e.total*100)}%`:`Loading model… ${(e.loaded/1048576).toFixed(1)} MB`;},error);
function error(e){$('#loading').textContent='Could not load model. Serve this folder with python -m http.server, or open the standalone viewer.';console.error(e)}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#cut').onchange=e=>cut(e.target.checked);
$('#trees').onchange=e=>{needsRender=true;model?.traverse(o=>{if(o.userData.layer?.startsWith('09'))o.visible=e.target.checked})};
$('#snapshot').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.download=`bahen-${view}.png`;a.href=renderer.domElement.toDataURL('image/png');a.click()};
$('#hide').onclick=()=>{if(innerWidth<=700){document.body.classList.toggle('mobile-controls');$('#hide').textContent=document.body.classList.contains('mobile-controls')?'Close controls':'Views & controls';}else{$('#panel').classList.toggle('collapsed');document.body.classList.toggle('controls-hidden');$('#hide').textContent=$('#panel').classList.contains('collapsed')?'Show controls':'Hide controls';}fitCamera();};if(innerWidth<=700)$('#hide').textContent='Views & controls';
$('#info').onclick=()=>$('#about').showModal();$('#close').onclick=()=>$('#about').close();
window.addEventListener('keydown',e=>{if(['INPUT','BUTTON','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(['w','a','s','d','q','e','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){activeKeys.add(e.key.toLowerCase());e.preventDefault()}});window.addEventListener('keyup',e=>activeKeys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>activeKeys.clear());
let wasMobile=innerWidth<=700;window.addEventListener('resize',()=>{const mobile=innerWidth<=700;if(mobile!==wasMobile){wasMobile=mobile;if(mobile){document.body.classList.remove('controls-hidden');$('#panel').classList.remove('collapsed');}else document.body.classList.remove('mobile-controls');if(mobile&&!compactTextures&&model){compactTextures=true;sizedTextures.clear();model.traverse(o=>{if(o.isMesh)sizeAtlas(closedMaterials.get(o)||o.material)});}setView(view);$('#hide').textContent=mobile?'Views & controls':($('#panel').classList.contains('collapsed')?'Show controls':'Hide controls');}else fitCamera();});
let needsRender=true;controls.addEventListener('change',()=>{needsRender=true});window.addEventListener('modelready',()=>{needsRender=true});window.addEventListener('resize',()=>{needsRender=true});
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(activeKeys.size){const f=new THREE.Vector3();camera.getWorldDirection(f);f.y=0;f.normalize();const r=new THREE.Vector3().crossVectors(f,camera.up).normalize();const d=new THREE.Vector3();for(const k of activeKeys){if(k==='w'||k==='arrowup')d.add(f);if(k==='s'||k==='arrowdown')d.sub(f);if(k==='d'||k==='arrowright')d.add(r);if(k==='a'||k==='arrowleft')d.sub(r);if(k==='e')d.y++;if(k==='q')d.y--;}d.multiplyScalar(dt*5);camera.position.add(d);controls.target.add(d)}controls.update();if(needsRender){renderer.render(scene,camera);needsRender=false}}requestAnimationFrame(frame);
